# Generated by Django 3.2.8 on 2021-10-08 21:37

from django.db import migrations, models
import django.db.models.deletion
import offers.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPoint',
            fields=[
                ('url', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор точки')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование точки')),
                ('description', models.TextField(verbose_name='Описание точки')),
            ],
            options={
                'verbose_name': 'Точка подачи предложений',
                'verbose_name_plural': 'Точки подачи предложений',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_target', models.CharField(choices=[(offers.models.OfferTarget['PRODUCTIVITY_INCREASE'], 'Повышение производительности труда и увеличение объемов производства'), (offers.models.OfferTarget['COST_REDUCE'], 'Снижение затрат'), (offers.models.OfferTarget['WORKING_CONDITION'], 'Улучшение организации условий труда'), (offers.models.OfferTarget['QUALITY_IMPROVING'], 'Повышение качества продукции'), (offers.models.OfferTarget['PRODUCTION_DOWNLOADS'], 'Сокращение простоев оборудования'), (offers.models.OfferTarget['OTHER'], 'Прочее')], max_length=255)),
                ('author_first_name', models.TextField(verbose_name='Имя')),
                ('author_second_name', models.TextField(verbose_name='Фамилия')),
                ('author_last_name', models.TextField(verbose_name='Отчество')),
                ('personnel_number', models.TextField(verbose_name='Табельный номер')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('problem_description', models.TextField(verbose_name='Описание проблемы')),
                ('suggestion_for_improvement', models.TextField(verbose_name='Предложение по улучшению')),
                ('expected_result', models.TextField(verbose_name='Ожидаемый результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offerpoint')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
