# Generated by Django 3.2.8 on 2021-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_target_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
