# Generated by Django 3.2.8 on 2021-10-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20211009_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_target',
            field=models.CharField(choices=[('Повышение производительности труда', 'Повышение производительности труда'), ('Снижение затрат', 'Снижение затрат'), ('Улучшение организации условий труда', 'Улучшение организации условий труда'), ('Повышение качества продукции', 'Повышение качества продукции'), ('Сокращение простоев оборудования', 'Сокращение простоев оборудования'), ('Прочее', 'Прочее')], max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='personnel_number',
            field=models.CharField(max_length=10, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='short_name',
            field=models.CharField(max_length=100, verbose_name='Короткое описание'),
        ),
    ]
