# Generated by Django 3.2.8 on 2021-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20211009_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpoint',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование точки'),
        ),
    ]
