# Generated by Django 3.2.8 on 2021-10-11 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_offerpoint_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerpoint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Точка подачи предложений', 'verbose_name_plural': 'Точки подачи предложений'},
        ),
        migrations.AddField(
            model_name='offerpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
