# Generated by Django 3.2.8 on 2021-10-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20211011_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='author_last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
    ]
